name: Generate Snake Animation

on:
    schedule:
        - cron: "0 */12 * * *"
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    generate:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Generate snake SVGs
              uses: Platane/snk/svg-only@v3
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                      dist/github-snake.svg?color_snake=#1278f6&color_dots=#1E293B,#1E40AF,#1278f6,#3B82F6,#5ce1e6
                      dist/github-snake-dark.svg?color_snake=#5ce1e6&color_dots=#1E293B,#1E40AF,#1278f6,#3B82F6,#5ce1e6

            - name: Push to output branch
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  publish_branch: output
                  force_orphan: true
